# Description: (Sim-only) Calendar format to set for the iOS Simulator
# value: e.g. gregorian
calendarFormat:

# Description: Bundle ID of the app under test. Useful for starting an app on a real device or 
# for using other caps which require the bundle ID during test startup. To run a test on a real 
# device using the bundle ID, you may omit the ‘app’ capability, but you must provide ‘udid’.
# value: e.g. io.appium.TestApp
bundleId: me.ele

# Description: Amount of time in ms to wait for instruments before assuming it hung and failing 
# the session
# value: e.g. 20000
launchTimeout:

# Description: (Sim-only) Force location services to be either on or off. Default is to keep 
# current sim setting.
# value: true or false
locationServicesEnabled:

# Description: (Sim-only) Set location services to be authorized or not authorized for app via plist, 
# so that location services alert doesn’t pop up. Default is to keep current sim setting.
# Note that if you use this setting you MUST also use the bundleId capability to send in your 
# app’s bundle ID.
# value: true or false
locationServicesAuthorized:

# Description: Accept iOS privacy access permission alerts (e.g., location, contacts, photos) 
# automatically if they pop up. Default is false.
# value: true or false
autoAcceptAlerts:

# Description: Dismiss iOS privacy access permission alerts (e.g., location, contacts, photos) 
# automatically if they pop up. Default is false.
# value: true or false
autoDismissAlerts:

# Description: Use native intruments lib (ie disable instruments-without-delay).
# value: true or false
nativeInstrumentsLib:

# Description: (Sim-only) Enable “real”, non-javascript-based web taps in Safari. 
# Default: false. Warning: depending on viewport size/ratio this might not accurately tap an element
# value: true or false
nativeWebTap:

# Description: (Sim-only) (>= 8.1) Initial safari url, default is a local welcome page
# value: e.g. https://www.github.com
safariInitialUrl:

# Description: (Sim-only) Allow javascript to open new windows in Safari. Default 
# keeps current sim setting
# value: true or false
safariAllowPopups:

# Description: (Sim-only) Prevent Safari from showing a fraudulent website warning. 
# Default keeps current sim setting.
# value: true or false
safariIgnoreFraudWarning:

# Description: (Sim-only) Whether Safari should allow links to open in new windows. 
# Default keeps current sim setting.
# value: true or false
safariOpenLinksInBackground: 

# Description: (Sim-only) Whether to keep keychains (Library/Keychains) when appium 
# session is started/finished
# value: true or false
keepKeyChains:

# Description: Where to look for localizable strings. Default en.lproj
# value: en.lproj
localizableStringsDir:

# Description: Arguments to pass to the AUT using instruments
# value: e.g., -myflag
processArguments:

# Description: The delay, in ms, between keystrokes sent to an element when typing.
# value: e.g., 100
interKeyDelay: 

# Description: Whether to show any logs captured from a device in the appium logs. Default false
# value: true or false
showIOSLog:

# Description: strategy to use to type test into a test field. Simulator default: oneByOne. 
# Real device default: grouped
# value: oneByOne, grouped or setValue
sendKeyStrategy:

# Description: Max timeout in sec to wait for a screenshot to be generated. default: 10
# value: e.g., 5
screenshotWaitTimeout:

# Description: The ios automation script used to determined if the app has been launched, 
# by default the system wait for the page source not to be empty. The result must be a boolean
# value: e.g. true;, target.elements().length > 0;, $.delay(5000); true;
waitForAppScript: 
