---
testSuite: "login"
preConditions:
- request: 
  name: "request1"
  url: ""
  method: ""
  body: ""
  headers: {'content-type':'application/json',}
- request: 
  name: ""
  url: ""
  method: ""
  body: ""
  headers: {'content-type':'application/json',}
testCases:
- test:
  name: "test name"
  url: "/api/path"
  method: "post"
  body: "{}"
  headers: {}
  cookie: {"":"",}
  assert: {"contain":"somestring","jsonPath":"json.path.para:value"}
- test: 
  name: "test name"
  url: "/api/path"
  method: "post"
  body: "{}"
  headers: {}
  assert: {"contain":"somestring","jsonPath":"json.path.para:value"}